global:
  refreshIntervalSeconds: 30
  onlyWithAnnotation: false

local:
  enabled: true

# remote:
#   allclusters:
#     - name: foobar
#       kubeconfigSecret:
#         name: foobar
#         namespace: default
