apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "landingpage.name" . }}
  labels:
    {{- include "landingpage.labels" . | nindent 4 }}
data:
  config.toml: |
    {{ .Values.config | toYaml | nindent 4 }}
